### PR TITLE
Kevin

### PR DESCRIPTION
**Pull request by rkevin99**
I had a need to 'serialize' some gwen dsl steps when multiple feature files are run parallelly. In order to do so i have provided 2 dsls : 
And I acquire a lock for 60 seconds
And I release a lock

The behaviour is as follows:
Then a lock is acquired for 60 seconds, no other thread will access the lock for at least 60 seconds.
If the locking thread takes more than 60 seconds, then other threads can potentially grab the lock.
If the lockingn thread finishes earlier than 60 seconds, any other thread can immediately get the lock and need not wait for  complete 60 seconds.
Effectively all steps between acquire and release get serialized when multiple threads are running (gwen in --parallel mode)  and the serialization has a guarantee for 60 seconds.

### CODE REVIEW

**Comment by bjuric** [comment]
Hi @rkevin99, 

I've reimplemented this as per my `@Synchronized StepDef` proposal above in a separate PR at the Gwen core level [here](https://github.com/gwen-interpreter/gwen/pull/45) so it can also be used by other engines.

I've also built the following snapshot for you to try it out and let us know how it goes before closing this PR and rolling it out. If it does not meet your needs, let us now also.
- [gwen-web-2.25.3-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.25.3-SNAPSHOT/gwen-web-2.25.3-SNAPSHOT.zip)

Cheers,
Branko

**Comment by rkevin99** [comment]
Hi BrankoThanks for the quick response.
This might solve my problem - but i need a small clarification.
What would happen if step 1 passes and step 2 fails ? Would one of the other feature files that were waiting, now seamlessly enter this synchronized StepDef ? Or would they be waiting endlessly for the earlier thread to run to completion ?
RegardsKevin Rodrigues.


   On Saturday, 25 August, 2018, 5:50:10 AM IST, Branko Juric <notifications@github.com> wrote:  
 
 
Hi Kevin,

Thanks for the PR. I see that what you're wanting is effectively a synchronization block around some steps. Perhaps an alternative approach to implementing this might be to introduce a @Synchronized annotation for StepDefs. All the steps in a StepDef with this annotation would then run in a single thread when called from any feature.

For example, the 3 steps in the following step def would run for one feature at a time when called by muntiple features running in parallel.
@Synchronized
@StepDef
Scenario: I run in single thread
     Given step 1
      When step 2
      Then step 3

The implementation would be greatly simplified and wouldn't require any wait, timeout, or lock management code.

Let me know if this would suit your needs.

**Comment by bjuric** [comment]
If step 2 fails it should not block..Feel free to test that out.

**Comment by rkevin99** [comment]
Hi Branko
Any updates on this ? A few more issues that i may have with the @synchronized keyword at a StepDef level is that  even when 'parallelization' is NOT required, some scenarios would be  synchronized through the StepDef one at a time, which could be unnecessary.
Also, if we need consecutive execution of a few of the StepDefs  together ( which could be a series of javascript executions ), then too i am constrained to implement @Synchronized for each of those StepDefs rather than one consolidated block of synchronization across the steps.
By providing an acquire and release lock DSL at a feature file level would provide more flexibility/control to the users of gwen framework.
Your framework is beautiful and can be used across a lot across nightly builds of different solutions so testing and 'time' to complete the tests can become very important  - especially if the testing is in sync with the development teams in an 'agile' development mode. One would like to avoid unnecessary synchronizations/delays as far as possible.
Let me know.
Thanks & RegardsKevin Rodrigues.
   On Monday, 27 August, 2018, 10:01:34 AM IST, Kevin Rodrigues <kevinmrodrigues@yahoo.com> wrote:  
 
 Hi BrankoThanks for the quick response.
This might solve my problem - but i need a small clarification.
What would happen if step 1 passes and step 2 fails ? Would one of the other feature files that were waiting, now seamlessly enter this synchronized StepDef ? Or would they be waiting endlessly for the earlier thread to run to completion ?
RegardsKevin Rodrigues.


   On Saturday, 25 August, 2018, 5:50:10 AM IST, Branko Juric <notifications@github.com> wrote:  
 
 
Hi Kevin,

Thanks for the PR. I see that what you're wanting is effectively a synchronization block around some steps. Perhaps an alternative approach to implementing this might be to introduce a @Synchronized annotation for StepDefs. All the steps in a StepDef with this annotation would then run in a single thread when called from any feature.

For example, the 3 steps in the following step def would run for one feature at a time when called by muntiple features running in parallel.
@Synchronized
@StepDef
Scenario: I run in single thread
     Given step 1
      When step 2
      Then step 3

The implementation would be greatly simplified and wouldn't require any wait, timeout, or lock management code.

Let me know if this would suit your needs.

**Comment by bjuric** [comment]
Hi Kevin,

These are good points. 

We can definitely suppress the sync blocks in the case of serial (non parallel) execution. I'll add a commit for that to the PR.

Regarding supporting an imperative style DSL at thefeature level, we would not wish to add that capability as we feel it would clutter feature files with technical details that really should be confined to meta. With little effort, you can achieve any synchronization you need. For example, to run multiple StepDefs in sync, just create a new higher level StepDef with @synchronozed annotation that calls all those StepDefs you need run synchronized. Each nested StepDef will then run in the synchronized block of the calling StepDef. We can also make a change to ensure that unncessary looks are not created again for nested calls 

Please let us know how you go with the snapshot build and we will then roll it out to a release.

Thanks,
Branko

**Comment by bjuric** [comment]
There are many things that could go wrong and lock up threads if we put the onus on the user to demarcate blocks in an imperative manner. We wish to keep Gwen simple and reliable and the annotation approach is flexible and robust.

**Comment by rkevin99** [comment]
Ok. Branko. Thx.
One question remains unanswered though:
What would happen if in a synchronized StepDef, step 1 passes and step 2 fails ? Would one of the other feature files that were waiting, now seamlessly enter this synchronized StepDef ? Or would they be waiting endlessly for the earlier (failed)  thread/step to run to completion ?

RegardsKevin Rodrigues.

   On Wednesday, 29 August, 2018, 12:12:05 PM IST, Branko Juric <notifications@github.com> wrote:  
 
 
There are many things that could go wrong and lock up threads if we put the onus on the user to demarcate blocks in an imperative manner. We wish to keep Gwen simple and reliable and the annotation approach is flexible and robust.

**Comment by bjuric** [comment]
I've built the snapshot below containing the change to ignore synchronized step defs in serial (non-parallel) execution mode. This does not however include logic to reuse locks in nested stepdefs from the caller, since iInheriting locks would introduce more overhead and risk in cases where non annotated stepdefs are called both directly and nested at the same time by different features. Therefore the user is responsible for annotating all StepDefs (and there will be no surprises).

Kevin, please retest using snapshot and let us know the outcome.

- [gwen-web-2.25.3-a4a1d51-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.25.3-a4a1d51-SNAPSHOT/gwen-web-2.25.3-a4a1d51-SNAPSHOT.zip)

**Comment by bjuric** [comment]
Also can you change the title of this PR from `Kevin` to something more descriptive of the request? Thanks

**Comment by bjuric** [comment]
Closing PR. This is being addressed at the Gwen core level [PR 45](https://github.com/gwen-interpreter/gwen/pull/45) instead.

**Pull request closed without merging**
